// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolyTrader.Infrastructure.Data;

#nullable disable

namespace PolyTrader.Infrastructure.Migrations
{
    [DbContext(typeof(PolyTraderDbContext))]
    [Migration("20260530071034_SyncPendingModel")]
    partial class SyncPendingModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("PolyTrader.Infrastructure.Entities.BalanceSnapshotEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CandleTime")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CashBalance")
                        .HasColumnType("REAL");

                    b.Property<double?>("Equity")
                        .HasColumnType("REAL");

                    b.Property<int>("PaperAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PaperAccountId", "CandleTime");

                    b.ToTable("BalanceSnapshots");
                });

            modelBuilder.Entity("PolyTrader.Infrastructure.Entities.CandleSnapshotEntity", b =>
                {
                    b.Property<long>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Close")
                        .HasColumnType("REAL");

                    b.Property<double>("High")
                        .HasColumnType("REAL");

                    b.Property<double>("Low")
                        .HasColumnType("REAL");

                    b.Property<double>("Open")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Time");

                    b.ToTable("CandleSnapshots");
                });

            modelBuilder.Entity("PolyTrader.Infrastructure.Entities.EngineSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActivePaperAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoRedeemEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BetStakeMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("BetStakePercent")
                        .HasColumnType("REAL");

                    b.Property<double>("BetStakeUsd")
                        .HasColumnType("REAL");

                    b.Property<double>("CommissionPercent")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LiveEntryOrderMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("MaxBetStakeUsd")
                        .HasColumnType("REAL");

                    b.Property<string>("PendingBetStakeMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PendingBetStakePercent")
                        .HasColumnType("REAL");

                    b.Property<double>("PendingBetStakeUsd")
                        .HasColumnType("REAL");

                    b.Property<double?>("PendingMaxBetStakeUsd")
                        .HasColumnType("REAL");

                    b.Property<string>("TradingMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivePaperAccountId");

                    b.ToTable("EngineSettings");
                });

            modelBuilder.Entity("PolyTrader.Infrastructure.Entities.MarketEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConditionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoTokenId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WindowEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WindowStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("YesTokenId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConditionId");

                    b.ToTable("Markets");
                });

            modelBuilder.Entity("PolyTrader.Infrastructure.Entities.PaperAccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Balance")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("InitialBalance")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PaperAccounts");
                });

            modelBuilder.Entity("PolyTrader.Infrastructure.Entities.PositionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AvgPrice")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarketId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SizeUsd")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MarketId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("PolyTrader.Infrastructure.Entities.SkippedBetEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CandleTime")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("InitialAsk")
                        .HasColumnType("REAL");

                    b.Property<double?>("InitialBid")
                        .HasColumnType("REAL");

                    b.Property<int>("MarketId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PaperAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Side")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("SignalPresent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkipDetail")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SkipReason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Trend")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketId");

                    b.HasIndex("CandleTime", "Mode", "PaperAccountId", "MarketId")
                        .IsUnique();

                    b.ToTable("SkippedBets");
                });

            modelBuilder.Entity("PolyTrader.Infrastructure.Entities.TradeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BetStakeFixedUsd")
                        .HasColumnType("REAL");

                    b.Property<string>("BetStakeMode")
                        .HasColumnType("TEXT");

                    b.Property<double?>("BetStakePercent")
                        .HasColumnType("REAL");

                    b.Property<long>("CandleTime")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ConfirmedSettledAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("EntryPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("EntryWavesJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MarketId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PaperAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PnlUsd")
                        .HasColumnType("REAL");

                    b.Property<string>("PolymarketOrderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProvisionalSettledAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RedeemedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("RequestedStakeUsd")
                        .HasColumnType("REAL");

                    b.Property<string>("SettlementSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("SettlementStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("StakeBalanceUsd")
                        .HasColumnType("REAL");

                    b.Property<double>("StakeUsd")
                        .HasColumnType("REAL");

                    b.Property<string>("Trend")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("WinPayoutRatio")
                        .HasColumnType("REAL");

                    b.Property<bool?>("Won")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CandleTime");

                    b.HasIndex("MarketId");

                    b.HasIndex("CandleTime", "Mode", "PaperAccountId")
                        .IsUnique();

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("PolyTrader.Infrastructure.Entities.EngineSettingsEntity", b =>
                {
                    b.HasOne("PolyTrader.Infrastructure.Entities.PaperAccountEntity", "ActivePaperAccount")
                        .WithMany()
                        .HasForeignKey("ActivePaperAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActivePaperAccount");
                });

            modelBuilder.Entity("PolyTrader.Infrastructure.Entities.PositionEntity", b =>
                {
                    b.HasOne("PolyTrader.Infrastructure.Entities.MarketEntity", "Market")
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Market");
                });

            modelBuilder.Entity("PolyTrader.Infrastructure.Entities.SkippedBetEntity", b =>
                {
                    b.HasOne("PolyTrader.Infrastructure.Entities.MarketEntity", "Market")
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Market");
                });

            modelBuilder.Entity("PolyTrader.Infrastructure.Entities.TradeEntity", b =>
                {
                    b.HasOne("PolyTrader.Infrastructure.Entities.MarketEntity", "Market")
                        .WithMany()
                        .HasForeignKey("MarketId");

                    b.Navigation("Market");
                });
#pragma warning restore 612, 618
        }
    }
}
